### ISSUE TITLE
Question . Вопрос

### ISSUE THREAD

**Issue by arstagaev** [mahwd/mahwd.github.io#1]
Hi! How did you deploy your project on Github Pages? Interesting, how to deploy Vue apps in Github:). I know how to deploy only js/Html projects but on Vue.. hard(

**Comment by mahwd** [comment]
Hi @arstagaev. Build your vue project then drop build files here as static webpage.

**Comment by arstagaev** [comment]
Thanks! 
And need write point in front of links
![image](https://user-images.githubusercontent.com/53790451/143826867-018249f9-76d2-429b-bc3a-079a478b8aa2.png)
